version: '3.3'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - '8069'
      - '8072'
    volumes:
      - 'odoo-data:/var/lib/odoo'
      - './config:/etc/odoo'
      - './addons:/mnt'
      - './addons/extra-addons:/mnt/extra-addons'
    networks:
      - default
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 150m
  db:
    image: 'postgres:10'
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=${password('postgres')}
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGPASS=${password('postgres')}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 20m
volumes:
  postgres-data: null
  odoo-data: null